INSERT INTO ABILITY_MODIFIER (ABILITY_SCORE, ABILITY_MODIFIER_POINTS)
SELECT 1, -5 FROM DUAL
UNION ALL
SELECT 2, -4 FROM DUAL
UNION ALL
SELECT 4, -3 FROM DUAL
UNION ALL
SELECT 6, -2 FROM DUAL
UNION ALL
SELECT 8, -1 FROM DUAL
UNION ALL
SELECT 10, 0 FROM DUAL
UNION ALL
SELECT 12, 1 FROM DUAL
UNION ALL
SELECT 14, 2 FROM DUAL
UNION ALL
SELECT 16, 3 FROM DUAL
UNION ALL
SELECT 18, 4 FROM DUAL
UNION ALL
SELECT 20, 5 FROM DUAL
UNION ALL
SELECT 22, 6 FROM DUAL
UNION ALL
SELECT 24, 7 FROM DUAL
UNION ALL
SELECT 26, 8 FROM DUAL
UNION ALL
SELECT 28, 9 FROM DUAL
UNION ALL
SELECT 30, 10 FROM DUAL;