INSERT INTO ABILITY (NAME)
SELECT "Strength" FROM DUAL
UNION ALL
SELECT "Dexterity" FROM DUAL
UNION ALL
SELECT "Constitution" FROM DUAL
UNION ALL
SELECT "Intelligence" FROM DUAL
UNION ALL
SELECT "Wisdom" FROM DUAL
UNION ALL
SELECT "Charisma" FROM DUAL