CREATE TABLE DICES (
  DICES_ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
  DICE_TYPE NUMBER NOT NULL,
  CONSTRAINT DICES_ID_pk PRIMARY KEY (DICES_ID),
  CONSTRAINT DICES_min_max CHECK (DICE_TYPE >= 3 AND DICE_TYPE <= 20)
);