CREATE TABLE ABILITY_MODIFIER (
  ABILITY_MODIFIER_ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
  ABILITY_SCORE NUMBER NOT NULL,
  ABILITY_MODIFIER NUMBER NOT NULL,
  CONSTRAINT ABILITY_MODIFIERS_pk PRIMARY KEY (ABILITY_MODIFIER_ID),
  CONSTRAINT ABILITY_SCORE_min_max CHECK (ABILITY_SCORE >= 1 AND ABILITY_SCORE <= 30),
  CONSTRAINT ABILITY_MODIFIER_min_max CHECK (ABILITY_MODIFIER >= -5 AND ABILITY_MODIFIER <= 10)
);