SELECT ABILITY_MODIFIER.ABILITY_MODIFIER
  FROM ABILITY_MODIFIER
  WHERE ABILITY_MODIFIER.ABILITY_SCORE = abilityScoreInput
  OR ABILITY_MODIFIER.ABILITY_SCORE = abilityScoreInput - 1;
  DBMS_OUTPUT.PUT_LINE(abilityModifier);