-- table of category names
CREATE TABLE ITEM_CATEGORY (
  ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL UNIQUE,
  NAME VARCHAR2(100) NOT NULL UNIQUE,
  CONSTRAINT ID PRIMARY KEY (ID)
);
-- tables of categories with different properties
CREATE TABLE ARMOR (
  ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL UNIQUE,
  ITEM_ID NUMBER NOT NULL UNIQUE,
  ARMOR_CATEGORY VARCHAR2(100) NOT NULL UNIQUE,
  ARMOR_CLASS NUMBER NOT NULL,
  STRENGTH NUMBER,
  STEALTH VARCHAR2(12),
  CONSTRAINT ID_PK PRIMARY KEY (ID),
  FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID)
);
CREATE TABLE WEAPON (
  ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL UNIQUE,
  ITEM_ID NUMBER NOT NULL UNIQUE,
  CONSTRAINT ID_PK PRIMARY KEY (ID),
  FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID)
);
-- master table
CREATE TABLE ITEM (
  ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL UNIQUE,
  NAME VARCHAR2(255) NOT NULL UNIQUE,
  ITEM_CATEGORY_ID VARCHAR2(255) NOT NULL,
  COST NUMBER,
  WEIGHT NUMBER,
  DESCRIPTION CLOB,
  FOREIGN KEY (ITEM_CATEGORY_ID) REFERENCES ITEM_CATEGORY(ID),
  CONSTRAINT ID_PK PRIMARY KEY (ID)
);