INSERT INTO ITEM_CATEGORY (NAME)
SELECT "Adventuring Gear" FROM DUAL
UNION ALL
SELECT "Armor" FROM DUAL
UNION ALL
SELECT "Potion" FROM DUAL
UNION ALL
SELECT "Scroll" FROM DUAL
UNION ALL
SELECT "Wand" FROM DUAL
UNION ALL
SELECT "Simple Melee Weapon" FROM DUAL
UNION ALL
SELECT "Simple Ranged Weapon" FROM DUAL
UNION ALL
SELECT "Martial Melee Weapon" FROM DUAL
UNION ALL
SELECT "Martial Ranged Weapon" FROM DUAL
UNION ALL
SELECT "Ammunition" FROM DUAL
UNION ALL
SELECT "Mount" FROM DUAL
UNION ALL
SELECT "Gemstone" FROM DUAL
UNION ALL
SELECT "Holy Symbol" FROM DUAL
UNION ALL
SELECT "Tool" FROM DUAL


UNION ALL
SELECT "Tack, Harness, and Drawn Vehicles" FROM DUAL




